%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Gergely\Dropbox\SK-COVID-19\data-sk.csv
%
% Auto-generated by MATLAB on 13-Mar-2020 13:01:59

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Day", "Date", "Confirmed", "Deaths"];
opts.VariableTypes = ["double", "string", "double", "double"];
opts = setvaropts(opts, 2, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 2, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\Gergely\Dropbox\SK-COVID-19\data-sk.csv", opts);

%% Convert to output type
Day = tbl.Day;
Date = tbl.Date;
Confirmed = tbl.Confirmed;
Deaths = tbl.Deaths;

%% Clear temporary variables
clear opts tbl