
%% Print


disp(['SARS-CoV-2 na Slovensku'])
disp(['============================'])
disp(['* Analýza ',datestr(now),''])
disp(' ')
disp('Exponenciálny model: (aktualny do konca dna)')
disp(['----------------------------'])
disp(['Overené prípady: ',num2str(NdPredicted(max(Day)+1)),' (',num2str(NdPredLow(2)),'-',num2str(NdPredHigh(2)),')']) %,'(',num2str(NdPredLow(max(Day)+1)),'-',NdPredHigh(max(Day)+1),')'])
disp(['Nové overené prípady: ',num2str(NdPredicted(max(Day)+1)-Nd(end)),' (',num2str(NdPredLow(2)-Nd(end)),'-',num2str(NdPredHigh(2)-Nd(end)),')']) %,'(',num2str(NdPredLow(max(Day)+1)),'-',NdPredHigh(max(Day)+1),')'])
disp(['Celkový predpokladaný pocet nakazených: ',num2str(NdSymptoms(max(Day)+1)),' (',num2str(NdSymptomsLow(max(Day)+1)),'-',num2str(NdSymptomsHigh(max(Day)+1)),')'])
%disp(['Predpokladaný dátum 100+ overených prípadov: ',datestr(d1+min(find(NdPredicted>100)))])
disp(['Predpokladaný dátum 1000+ overených prípadov: ',datestr(d1+min(find(NdPredicted>1000)))])
disp(['Predpokladaný dátum prvého nakazenia: ',datestr(d1+firstCase)])
disp(['Predpokladaný skutocný pocet infikovaných nultý den: ',num2str(round(N0)),' (',num2str(round(ci(1,2))),'-',num2str(round(ci(2,2))),'), (6-Mar-2020)'])
disp(['Faktor nárastu: ',num2str(round((gF-1)*100*10)/10),'% (',num2str(round((ci(1,1)-1)*100*10)/10),'%-',num2str(round((ci(2,1)-1)*100*10)/10),'%), R^2=',num2str(R2)])
disp(['Zdvojenie poctu prípadov za: ',num2str(round((70/((gF-1)*100))*10)/10),' dní'])
disp(' ')
disp(['SIR model: (aktualny do konca dna)'])
disp(['----------------------------'])
disp(['Odhad základného reprodukcného císla R0: ',num2str(round(R0est*10)/10),', (MSE: ',num2str(MSE),')'])
disp(['Miera infekcie 1/beta: ',num2str(round(betaInvEst*10)/10),', (MSE: ',num2str(MSE),')'])
disp(['Miera odstránenia prípadov 1/gamma: ',num2str(round(gammaInvEst*10)/10),', (MSE: ',num2str(MSE),')'])
disp(['Overené prípady: ',num2str(round(NdSIRnext))])
disp(['Nové overené prípady: ',num2str(NdSIRnext-Nd(end))])
disp(['Celkový predpokladaný pocet nakazených: ',num2str(IsimSymptoms(max(Day)+round(symptoms)))])
disp(['Predpokladaný dátum 1000+ overených prípadov: ',datestr(d1+max(Day)+min(find(IsimPred>1000)))])
disp(['Predpokladaný dátum prvého nakazenia: ',datestr(d1-d0est)])
%disp(['Predpokladaný skutocný pocet infikovaných nultý den: ',num2str(round(N0est)),' (6-Mar-2020)'])
disp(['Faktor nárastu: ',num2str(round((gFSIR*10))/10),'%'])
disp(['Zdvojenie poctu prípadov za: ',num2str( round((70/((gFSIR))*10))/10),' dní'])
disp(' ')
disp(['Stav testovania k ',datestr(dt-1),' (vratane)'])
disp(['----------------------------'])
disp(['Celkove testy na mil. obyvatelov: ',num2str(round(popTest(end)))])
disp(['Nove testy za den na mil. obyvatelov: ',num2str( round(newTest(end)/popSize))])
disp(['Denná zmena intenzity testovania: ',num2str(round(changeTest)),'%'])
disp(['Trend zmeny intenzity testovania: ',num2str(round((testA))),'% (lineárny fit)'])
disp(['============================='])
disp(['Viac na: http://covid19.gergelytakacs.com'])